### ISSUE TITLE
Code error in " ayFXplayer.c"

### ISSUE THREAD

**Issue by ericb59** [mvac7/SDCC_ayFXplayer_Lib#1]
Hello,

There is a bug in **ayFXplayer.c**, routine : **ayFX_Decode()**
If the sound FX is played on channel C all is ok, but If it played on channel A or B, it can crash, because IX register is not always retrieved.

Line **332** and **346**
replace : `RET NZ` by    `JR	NZ,END_ayFXdecode`

Other solution is to convert the code to the new SDCC passing value convention.
see you

**Comment by mvac7** [comment]
Thank you very much Eric! 
I'll try to make the correction shortly.
